# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A8TmFnkCfWdrmIpVdMhzpHovqyButxzF
"""

# 'pip' is Python's package installer.
# The '-q' flag means "quiet" — don't print every download step (keeps output clean).
# In Colab, '!pip install' is the standard way to install libraries.

!pip install -q yellowbrick

# After installing, let's import it to confirm it works:
import yellowbrick
print(f"✅ yellowbrick version {yellowbrick.__version__} installed successfully!")

# Import the libraries we need.
# - pandas: for data tables (like Excel in Python)
# - sklearn.datasets: has several built-in datasets for learning

import pandas as pd
from sklearn.datasets import load_iris

# Load the iris dataset into a variable.
iris = load_iris()

# Convert it into a pandas DataFrame so it looks nice and is easy to work with.
# 'iris.data' = the measurements (features)
# 'iris.feature_names' = column names like 'sepal length (cm)'
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Add a 'species' column.
# 'iris.target' is numbers (0, 1, 2); 'iris.target_names' maps them to flower names.
df['species'] = [iris.target_names[i] for i in iris.target]

# Show the first 5 rows to see what the data looks like.
df.head()

# Quick exploration — how many flowers of each type?
# value_counts() counts how many times each unique value appears.
print("Flowers per species:")
print(df['species'].value_counts())

# Show basic statistics (mean, min, max, etc.) for all numeric columns.
print("\nBasic statistics:")
df.describe()

# Import plotting libraries.
# - matplotlib.pyplot: the core plotting library in Python
# - seaborn: prettier, statistics-focused plots built on top of matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

# Set a clean visual theme.
sns.set_theme(style="whitegrid")

# Create a pairplot — shows how every feature relates to every other feature,
# colored by species. Great way to see if the classes are separable.
# 'hue="species"' means color each dot by the species column.
sns.pairplot(df, hue="species", height=2)

# Add a title above the whole figure.
plt.suptitle("Iris Flower Measurements by Species", y=1.02)

# Display the plot.
plt.show()

# Import the tools we need from scikit-learn.
# - train_test_split: splits data into training and testing sets
# - RandomForestClassifier: the ML model we'll use (it's like many decision trees combined)
# - accuracy_score, classification_report: to measure how good our model is

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Step 7a: Separate features (X) from the target label (y).
# X = the measurements; y = the species we want to predict.
X = df[iris.feature_names]   # all 4 measurement columns
y = df['species']             # the species column

# Step 7b: Split the data — 80% for training, 20% for testing.
# 'random_state=42' makes the split reproducible (same split every time we run).
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,       # 20% of data kept for testing
    random_state=42,     # "seed" for randomness, so results are repeatable
    stratify=y           # keep the same class proportions in train and test
)

print(f"Training set size: {len(X_train)} flowers")
print(f"Testing set size:  {len(X_test)} flowers")

# Step 7c: Create the model.
# n_estimators=100 means "build 100 decision trees and let them vote".
# random_state=42 again for reproducibility.
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Step 7d: Train (fit) the model on our training data.
# This is where the ML magic happens — it learns patterns from X_train to predict y_train.
model.fit(X_train, y_train)

print("✅ Model training complete!")

# Step 7e: Use the trained model to predict on the test set (flowers it has never seen).
y_pred = model.predict(X_test)

# Step 7f: Measure accuracy — what fraction of predictions were correct.
accuracy = accuracy_score(y_test, y_pred)
print(f"🎯 Model Accuracy: {accuracy * 100:.2f}%")

# Step 7g: Show a detailed breakdown per species.
# 'precision' = of the ones we said were X, how many really were X
# 'recall' = of all the real X, how many did we catch
# 'f1-score' = balance of the two above
print("\nDetailed Performance:")
print(classification_report(y_test, y_pred))

# Import joblib — a library that efficiently saves Python objects to disk.
import joblib
import os

# Decide where to save the model.
# We'll put it in our Drive, inside a folder called 'DS_Lab_Week7'.
save_folder = '/content/drive/MyDrive/DS_Lab_Week7'

# Create the folder if it doesn't already exist.
# 'exist_ok=True' means: don't raise an error if the folder is already there.
os.makedirs(save_folder, exist_ok=True)

# Full path for the saved model file.
# '.pkl' is the standard extension for pickled (saved) Python objects.
model_path = os.path.join(save_folder, 'iris_rf_model.pkl')

# Save the model!
joblib.dump(model, model_path)

print(f"✅ Model saved successfully to: {model_path}")

# Verify the file is there by listing the folder.
!ls -lh "{save_folder}"

# Load the saved model back from Drive.
loaded_model = joblib.load(model_path)
print("✅ Model loaded from Drive!")

# Make up a new flower's measurements.
# Order must match training: sepal length, sepal width, petal length, petal width (all in cm).
new_flower = [[5.1, 3.5, 1.4, 0.2]]   # double brackets because the model expects a 2D input

# Predict which species this flower is.
prediction = loaded_model.predict(new_flower)

# Also get the probability for each species (how confident the model is).
probabilities = loaded_model.predict_proba(new_flower)

print(f"\n🌸 New flower measurements: {new_flower[0]}")
print(f"🎯 Predicted species: {prediction[0]}")
print(f"\nConfidence for each species:")
for species, prob in zip(loaded_model.classes_, probabilities[0]):
    print(f"   {species:15s}: {prob * 100:.2f}%")

